const EVENT_TYPES = {
  ACCOUNT_CREATED: "ACCOUNT_CREATED",

  MONEY_DEPOSITED: "MONEY_DEPOSITED",

  MONEY_WITHDRAWN: "MONEY_WITHDRAWN",

  TRANSFER_SENT: "TRANSFER_SENT",

  TRANSFER_RECEIVED: "TRANSFER_RECEIVED",
};

module.exports = EVENT_TYPES;